name: Fetch and Convert AdGuard to Surge Rules

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/adguard-surge.yml"
      - "tools/adguard-surge/**"
  schedule:
    - cron: "0 0 */2 * *"

permissions:
  contents: write

concurrency:
  group: rule-updates-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  generate-rules:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/adguard-surge

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: tools/adguard-surge
        run: npm install --package-lock=false

      - name: Generate Rules
        working-directory: tools/adguard-surge
        run: npm start

      - name: Commit and push changes
        working-directory: .
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f -A dist/surge/
          if ! git diff --staged --quiet; then
            git commit -m 'actions: Update AdGuard Surge domain sets'
            git pull --rebase origin main
            git push origin HEAD:main
          else
            echo 'No changes to commit'
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
